# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20160404_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=155),
        ),
    ]
