# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20160417_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('DEMOCRATIC', 'Democratic'), ('REPUBLICAN', 'Republican')], default='Republican', max_length=15),
            preserve_default=False,
        ),
    ]
