# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_candidate_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Democratic', 'Democratic'), ('Republican', 'Republican')], max_length=15),
        ),
    ]
